/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LeaguesLeaugeIdImport } from './routes/leagues.$leaugeId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LeaguesLeaugeIdRoute = LeaguesLeaugeIdImport.update({
  id: '/leagues/$leaugeId',
  path: '/leagues/$leaugeId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/leagues/$leaugeId': {
      id: '/leagues/$leaugeId'
      path: '/leagues/$leaugeId'
      fullPath: '/leagues/$leaugeId'
      preLoaderRoute: typeof LeaguesLeaugeIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leagues/$leaugeId': typeof LeaguesLeaugeIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leagues/$leaugeId': typeof LeaguesLeaugeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/leagues/$leaugeId': typeof LeaguesLeaugeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/leagues/$leaugeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/leagues/$leaugeId'
  id: '__root__' | '/' | '/leagues/$leaugeId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaguesLeaugeIdRoute: typeof LeaguesLeaugeIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaguesLeaugeIdRoute: LeaguesLeaugeIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/leagues/$leaugeId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/leagues/$leaugeId": {
      "filePath": "leagues.$leaugeId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
