/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeaguesLeagueIdRouteImport } from './routes/leagues.$leagueId'
import { Route as LeagueYahooLeague_keyRouteImport } from './routes/league.yahoo.$league_key'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesLeagueIdRoute = LeaguesLeagueIdRouteImport.update({
  id: '/leagues/$leagueId',
  path: '/leagues/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueYahooLeague_keyRoute = LeagueYahooLeague_keyRouteImport.update({
  id: '/league/yahoo/$league_key',
  path: '/league/yahoo/$league_key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/league/yahoo/$league_key': typeof LeagueYahooLeague_keyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/league/yahoo/$league_key': typeof LeagueYahooLeague_keyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/league/yahoo/$league_key': typeof LeagueYahooLeague_keyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/leagues/$leagueId'
    | '/league/yahoo/$league_key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/leagues/$leagueId'
    | '/league/yahoo/$league_key'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/leagues/$leagueId'
    | '/league/yahoo/$league_key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  LeaguesLeagueIdRoute: typeof LeaguesLeagueIdRoute
  LeagueYahooLeague_keyRoute: typeof LeagueYahooLeague_keyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$leagueId': {
      id: '/leagues/$leagueId'
      path: '/leagues/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof LeaguesLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/yahoo/$league_key': {
      id: '/league/yahoo/$league_key'
      path: '/league/yahoo/$league_key'
      fullPath: '/league/yahoo/$league_key'
      preLoaderRoute: typeof LeagueYahooLeague_keyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  LeaguesLeagueIdRoute: LeaguesLeagueIdRoute,
  LeagueYahooLeague_keyRoute: LeagueYahooLeague_keyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
