/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LeaguesHomeImport } from './routes/LeaguesHome'
import { Route as HomeImport } from './routes/Home'

// Create/Update Routes

const LeaguesHomeRoute = LeaguesHomeImport.update({
  id: '/LeaguesHome',
  path: '/LeaguesHome',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/Home',
  path: '/Home',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Home': {
      id: '/Home'
      path: '/Home'
      fullPath: '/Home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/LeaguesHome': {
      id: '/LeaguesHome'
      path: '/LeaguesHome'
      fullPath: '/LeaguesHome'
      preLoaderRoute: typeof LeaguesHomeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/Home': typeof HomeRoute
  '/LeaguesHome': typeof LeaguesHomeRoute
}

export interface FileRoutesByTo {
  '/Home': typeof HomeRoute
  '/LeaguesHome': typeof LeaguesHomeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/Home': typeof HomeRoute
  '/LeaguesHome': typeof LeaguesHomeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/Home' | '/LeaguesHome'
  fileRoutesByTo: FileRoutesByTo
  to: '/Home' | '/LeaguesHome'
  id: '__root__' | '/Home' | '/LeaguesHome'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomeRoute: typeof HomeRoute
  LeaguesHomeRoute: typeof LeaguesHomeRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRoute,
  LeaguesHomeRoute: LeaguesHomeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/Home",
        "/LeaguesHome"
      ]
    },
    "/Home": {
      "filePath": "Home.tsx"
    },
    "/LeaguesHome": {
      "filePath": "LeaguesHome.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
