name: Node Integration Test

on: 
  push:
    paths:
    - 'backend/**'
    - '.github/workflows/node-backend.yml'


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      YAHOO_CONSUMER_KEY: yahooEnv.YAHOO_CONSUMER_KEY
      YAHOO_CONSUMER_SECRET: yahooEnv.YAHOO_CONSUMER_SECRET
      YAHOO_STATE_SECRET: yahooEnv.YAHOO_STATE_SECRET
      YAHOO_REDIRECT_URI: yahooEnv.YAHOO_REDIRECT_URI
      JWT_SECRET: JWT_SECRET
      DB_URL: DB_URL
      DB_URI: DB_URI
      SECRET_KEY: SECRET_KEY

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node 22.16.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'

      - name: Install dependencies
        run: npm install

      - name: Test with Jest
        run: npm test
