name: Sleeper PlayerIDs Update

on:
  schedule:
    - cron: "0 */6 * * *"  # 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ENV

    env: 
      DB_URI: ${{ secrets.DB_URI }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_USER: ${{ secrets.REDIS_USER }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: ./backend/database_scripts
        run: | 
          python -m pip install --upgrade pip
          pip install requests pymongo python-dotenv redis

      - name: Sleeper Trade Market Crawler
        working-directory: ./backend/database_scripts
        run: |
          python sleeper_trade_market.py
